version: "3.7"
services:
    app:
        build:
            args:
                user: invoicesender
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: invoicesender
        container_name: invoicesender-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker-compose/php/invoicesender.ini:/usr/local/etc/php/conf.d/invoicesender.ini
        networks:
            - invoicesender
    db:
        image: mysql:8
        container_name: invoicesender-db
        restart: unless-stopped
        ports:
            - 3308:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql/init:/docker-entrypoint-initdb.d
            - ./docker-compose/mysql/persistent:/var/lib/mysql
        networks:
            - invoicesender
    nginx:
        image: nginx:1.21-alpine
        container_name: invoicesender-nginx
        restart: unless-stopped
        ports:
            - 8081:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - invoicesender
networks:
    invoicesender:
        driver: bridge